### ISSUE TITLE
"Unexpected token: name (CardComponent)" on Ionic Production Build

### ISSUE THREAD

**Issue by XPanniX** [ViCode/ng2-swipe-cards#16]
I just tried to run an Ionic production build (`ionic run android --prod`) on my android phone and this error showed up in the build process:

```BASH
[00:22:40]  uglifyjs failed: SyntaxError: Unexpected token: name (CardComponent) 
[00:22:40]  ionic-app-script task: "build" 
[00:22:40]  Error: SyntaxError: Unexpected token: name (CardComponent) 
Error
    at new JS_Parse_Error (eval at <anonymous> (/home/jan/IonicProjects/MeetsApp/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1545:18)
    at js_error (eval at <anonymous> (/home/jan/IonicProjects/MeetsApp/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1553:11)
    at croak (eval at <anonymous> (/home/jan/IonicProjects/MeetsApp/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2092:9)
    at token_error (eval at <anonymous> (/home/jan/IonicProjects/MeetsApp/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2100:9)
    at unexpected (eval at <anonymous> (/home/jan/IonicProjects/MeetsApp/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2106:9)
    at semicolon (eval at <anonymous> (/home/jan/IonicProjects/MeetsApp/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2126:56)
    at simple_statement (eval at <anonymous> (/home/jan/IonicProjects/MeetsApp/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2317:73)
    at eval (eval at <anonymous> (/home/jan/IonicProjects/MeetsApp/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2186:19)
    at eval (eval at <anonymous> (/home/jan/IonicProjects/MeetsApp/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2139:24)
    at block_ (eval at <anonymous> (/home/jan/IonicProjects/MeetsApp/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2432:20)
```

This error can also be reproduced with your [Ionic Demo](https://github.com/ViCode/ng2-swipe-cards-ionic-demo)

**Comment by ViCode** [comment]
Hi!

I did some search about this error and it seems to be specific at ionic-app-script: https://github.com/driftyco/ionic-app-scripts/issues/239

The two solutions are:

> edit node_modules/@ionic/app-scripts/package.json file. Then in that file update uglify-js like this "uglify-js": "git+https://github.com/mishoo/UglifyJS2.git#harmony".
> 
> Then after that execute npm install (make sure right now you're at node_modules/@ionic/app-scripts

or in case you don't need the uglify:

> You can disable minification by running ionic run android --aot

**Comment by chrisnicola** [comment]
Why was this closed it is still a serious issue with Ionic that it isn't working with AoT properly.
